### ISSUE TITLE
Cross platform support

### ISSUE THREAD

**Issue by ghost** [dhsavell/vdcrpt#11]
Any possible support for Linux and Macos?

Thanks

**Comment by dhsavell** [comment]
Thanks for your interest. I don't have a mac to test on, but I should be able to make a Linux package. If you're willing to run from source, it might work out-of-the-box if you have ffmpeg installed.

**Comment by branchpanic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set up Linux AppImage deployment](https://trello.com/c/opxAn0FJ/6-set-up-linux-appimage-deployment)

**Comment by branchpanic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set up macOS bundle deployment](https://trello.com/c/HBjGPBMh/4-set-up-macos-bundle-deployment) [edit: sorry, forgot to disable this before linking. finally working on it, though]

**Comment by branchpanic** [comment]
.app for macOS and .AppImage for Linux are available starting in 22.04.01. https://github.com/branchpanic/vdcrpt/releases/tag/v22.04.01
