### ISSUE TITLE
Targeted corruptions

### ISSUE THREAD

**Issue by dhsavell** [dhsavell/vdcrpt#9]
If adding exact start times for corruption was possible, vdcrpt would go from novel to legitimately useful for glitch art. The big problems are:

- How do we get from a timecode to offset in bytes?
- Should we fiddle with nearby frame types to exaggerate the effect? If so, how? (This is semi-related, but seems like it should be a part of a different mode)

Perhaps reading through the avidemux source will help me figure this out.

A brute-force idea is to split the video at the desired time, then start corrupting the second one right after the header. This would not allow for advanced I/P frame effects. It's a very hacky solution but could give some subset of users what they want.

**Comment by branchpanic** [comment]
Spent some time studying [ucnv/aviglitch](https://github.com/ucnv/aviglitch) and I have a clearer idea of how we can mess with specific frames. I'll reopen this eventually.
